# Generated by Django 3.2.2 on 2022-03-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('authors', models.CharField(default='', max_length=200)),
                ('rating', models.CharField(default='', max_length=70)),
                ('language', models.CharField(default='', max_length=70)),
                ('num_pag', models.CharField(default='', max_length=70)),
                ('rating_count', models.CharField(default='', max_length=70)),
                ('text_review_count', models.CharField(default='', max_length=70)),
                ('publiacation_date', models.CharField(blank=True, default='', max_length=150)),
                ('publisher', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
