# Generated by Django 3.2.2 on 2022-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220311_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='text_reviews_count',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
